version: '3.7'
services:
    db:
        image: mysql
        container_name: "mysql"
        command: ["--default-authentication-plugin=mysql_native_password"]
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: symfony
            MYSQL_USER: symfony
            MYSQL_PASSWORD: symfony
    php:
        build: ./back/php-fpm
        container_name: "php"
        ports:
            - "9000:9001"
        volumes:
            - ../back:/var/www/symfony:cached
            - ../log/symfony:/var/www/symfony/var/log:cached
        links:
            - db
        extra_hosts:
            - "docker-host.localhost:127.0.0.1"
    nginx:
        build: ./back/nginx
        container_name: "nginx"
        ports:
            - "80:80"
            - "8000:8000"
        links:
            - php
        volumes:
            - ../back:/var/www/symfony:cached
            - ../log/symfony:/var/www/symfony/var/log:cached
            - ../log/nginx:/var/log/nginx
    nuxt:
      build: ./front
      container_name: "nuxt"
      volumes:
          - ../front:/var/www/html/nuxt
      ports:
        - "3000:3000"
    # elk:
    #     image: willdurand/elk
    #     ports:
    #         - "81:80"
    #     volumes:
    #         - ./elk/logstash:/etc/logstash:cached
    #         - ./elk/logstash/patterns:/opt/logstash/patterns:cached
    #         - ./logs/symfony:/var/www/symfony/var/log:cached
    #         - ./logs/nginx:/var/log/nginx:cached